steps: 3000
time_step: 0.1
save_directory: '.'
record_collisions: true
runs: 10000
run_index: 0
scenario:
  type: Cross
  agent_margin: 0.1
  side: 4
  target_margin: 0.1
  tolerance: 0.5
  groups:
    -
      type: thymio
      number: 20
      radius: 0.08
      control_period: 0.1
      speed_tolerance: 0.02
      kinematics:
        type: 2WDiff
        wheel_axis: 0.094
        max_speed: 0.166
      behavior:
        type: HL
        optimal_speed: 0.12
        horizon: 5.0
        tau:
          sampler: uniform
          from: 0.0
          to: 1.0
          once: true
        eta:
          sampler: uniform
          from: 0.0
          to: 1.0
          once: true
        safety_margin:
          sampler: uniform
          from: 0.0
          to: 0.1
          once: true
      state_estimation:
        type: Bounded
        range_of_view: 5.0
